apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-renew-config
data:
  cert-renew: |
    #!/bin/bash

    export DOMAINS='corekube.com www.corekube.com'
    export EMAIL="corekube@gmail.com"
    export CRON_FREQUENCY="0 16 1 * *"
    export LETSENCRYPT_DIR="/srv/etc/letsencrypt"
    export LETSENCRYPT_ENDPOINT="https://acme-v01.api.letsencrypt.org/directory"
